
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author danie
 */

public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    String title = "LibraryManagementApp";
    ImageIcon img = new ImageIcon("C:\\Users\\danie\\OneDrive\\Desktop\\book.png");
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        booksListButton = new javax.swing.JButton();
        addBooksButton = new javax.swing.JButton();
        addStaffButton = new javax.swing.JButton();
        showStaffButton = new javax.swing.JButton();
        removeBooksButton = new javax.swing.JButton();
        removeStaffButton = new javax.swing.JButton();
        modifyAdminButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setText("Main Menu");

        booksListButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        booksListButton.setText("Books List");
        booksListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booksListButtonActionPerformed(evt);
            }
        });

        addBooksButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addBooksButton.setText("Add Books");
        addBooksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBooksButtonActionPerformed(evt);
            }
        });

        addStaffButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addStaffButton.setText("Add Staff");
        addStaffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStaffButtonActionPerformed(evt);
            }
        });

        showStaffButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        showStaffButton.setText("Staff ");
        showStaffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showStaffButtonActionPerformed(evt);
            }
        });

        removeBooksButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        removeBooksButton.setText("Remove Book");
        removeBooksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBooksButtonActionPerformed(evt);
            }
        });

        removeStaffButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        removeStaffButton.setText("Remove Staff");
        removeStaffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeStaffButtonActionPerformed(evt);
            }
        });

        modifyAdminButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        modifyAdminButton.setText("Modify Admin");
        modifyAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyAdminButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(removeBooksButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addBooksButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(booksListButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(removeStaffButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showStaffButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addStaffButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(modifyAdminButton)
                .addGap(131, 131, 131))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showStaffButton)
                    .addComponent(booksListButton))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStaffButton)
                    .addComponent(addBooksButton))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeStaffButton)
                    .addComponent(removeBooksButton))
                .addGap(18, 18, 18)
                .addComponent(modifyAdminButton)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void booksListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booksListButtonActionPerformed
        BooksList bl = new BooksList();
        bl.setResizable(false);
        bl.setTitle(title);
        bl.setIconImage(img.getImage());
        bl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_booksListButtonActionPerformed

    private void addBooksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBooksButtonActionPerformed
        AddBooks addBooks = new AddBooks();
        addBooks.setResizable(false);
        addBooks.setTitle(title);
        addBooks.setIconImage(img.getImage());
        addBooks.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addBooksButtonActionPerformed

    private void showStaffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showStaffButtonActionPerformed
        StaffList staff = new StaffList();
        staff.setResizable(false);
        staff.setTitle(title);
        staff.setIconImage(img.getImage());
        staff.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_showStaffButtonActionPerformed

    private void addStaffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStaffButtonActionPerformed
        AddStaff addStaff = new AddStaff();
        addStaff.setResizable(false);
        addStaff.setTitle(title);
        addStaff.setIconImage(img.getImage());
        addStaff.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addStaffButtonActionPerformed

    private void removeStaffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeStaffButtonActionPerformed
        RemoveStaff removeStaff = new RemoveStaff();
        removeStaff.setResizable(false);
        removeStaff.setTitle(title);
        removeStaff.setIconImage(img.getImage());
        removeStaff.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_removeStaffButtonActionPerformed

    private void removeBooksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBooksButtonActionPerformed
        RemoveBooks rB = new RemoveBooks();
        rB.setResizable(false);
        rB.setTitle(title);
        rB.setIconImage(img.getImage());
        rB.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_removeBooksButtonActionPerformed

    private void modifyAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyAdminButtonActionPerformed
        ModifyAdmin mA = new ModifyAdmin();
        mA.setResizable(false);
        mA.setTitle(title);
        mA.setIconImage(img.getImage());
        mA.setVisible(true);
        this.dispose();
              
    }//GEN-LAST:event_modifyAdminButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBooksButton;
    private javax.swing.JButton addStaffButton;
    private javax.swing.JButton booksListButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton modifyAdminButton;
    private javax.swing.JButton removeBooksButton;
    private javax.swing.JButton removeStaffButton;
    private javax.swing.JButton showStaffButton;
    // End of variables declaration//GEN-END:variables
}
